// <auto-generated />
namespace AICloud.Accounts.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_id_as_guid_in_accountdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_id_as_guid_in_accountdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202010121823229_added_id_as_guid_in_accountdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
