// <auto-generated />
namespace AICloud.Accounts.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rrearranging_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rrearranging_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202010061929228_rrearranging_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
