// <auto-generated />
namespace AICloud.Accounts.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_ledger_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ledger_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202009301805339_added_ledger_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
